config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper

  scope :api, defaults: { format: :json } do
    scope :v1 do
      devise_for :users
    end
  end

  resources :services

namespace :api do
  namespace :v1 do
    post 'registrations' => 'registrations#create'

    get 'services' => 'services#index'
    get 'services/:id' => 'services#show'
    post 'services' => 'services#create'

  end
end

use_doorkeeper do
  skip_controllers :authorizations, :applications,
    :authorized_applications
end

end

app/models/service.rb
class Service
  include Mongoid::Document
  include Geocoder::Model::Mongoid


  field :name, type: String
  field :description, type: String
  field :category, type: String
  field :status, type: Mongoid::Boolean
  # field :address, type: String
  field :coordinates, :type => Array


  # geocoded_by :address               # can also be an IP address
  # after_validation :geocode          # auto-fetch coordinates

  # reverse_geocoded_by :coordinates
  # after_validation :reverse_geocode  # auto-fetch address

  belongs_to :user, dependent: :destroy




  # after_validation :reverse_geocode, if: ->(obj){ obj.coordinates.present? }
  # after_validation :geocode, if: ->(obj){ obj.address.present? }

end

app/controllers/api/v1/services_controller.rb
class Api::V1::ServicesController < ApplicationController
  before_action :doorkeeper_authorize!, except: [:index, :show, :create]

  respond_to :json

  #Get all services(This method should not be exposed to the users in a production environment)
  def index
    @services = Service.all
    # respond_with @services

    render :status => 200,
           :json => { :success => true,
                      :data => @services }
  end

  #Get a service with a given id
  def show
  	begin
      service = Service.find(user_params[:id])
  	rescue Mongoid::Errors::DocumentNotFound => e
      service = nil  		
    end

    if service
      render status: 200,
        json: {:data => service}
      return
    else
      warden.custom_failure!
      render json: { success: false, error: 'Service not found' }, status: 404
    end
  end

  def create
    service_information = request.raw_post
    data_parsed = JSON.parse(service_information)

    service_hash = json_to_service_validator(data_parsed)
    new_service = service_hash[:data]
    if(new_service and new_service.save)
      render status: 200,
           json: {id: new_service.id}
    else
      if(new_service)
        errors = new_service.errors.full_messages.to_sentence
      else
        errors = quiz_hash[:errors]
      end
      render status: 405,
           json: {error: errors}
    end
 
  end

 private
  def user_params
    params.permit(:id)
  end


  # It validates the json object and returns the corresponging service
  def json_to_service_validator(json)
    if(json.count  == 5 and
       json['name'] and
       json['description'] and
       json['category'] and
       json['status'] and
       json['coordinates'] and
       json['coordinates'].count  == 2)
      
      service = Service.new (json)
      retval = {:data => service}
    else
      return {:errors => "The json object to create a service is wrong"}
    end
    return retval
  end

end

app/controllers/services_controller.rb
require 'pp'

class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
    # @service.address = request.location
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    p "HEREHEREHERE"
    pp service_params

    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      p "HEREHEREHERE"
      p service_params
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      well_params = params.require(:service).permit(:name, :description, :coordinates, :category, :status)
      well_params[:coordinates] = well_params[:coordinates].split(" ").map { |s| s.to_f }
      well_params
    end
end

app/helpers/services_helper.rb
module ServicesHelper

	def self.random_location_from_given_pos(location, distance)
		distanceInMeter = distance
        directionInDegrees = rand(0 ... 360)

        lat = location[0]
        long = location[1]

        radDirection = directionInDegrees * Math::PI / 180

        dx = distanceInMeter * Math::cos(radDirection) 
        dy = distanceInMeter * Math::sin(radDirection)

        radLat = lat  * Math::PI / 180

        deltaLongitude = dx/(111320 * Math::cos(radLat))
        deltaLatitude = dy/110540                   

        endLat = lat + deltaLatitude
        endLong = long + deltaLongitude

        return [endLat, endLong]
	end
end

app/views/services/_form.html.erb
<script src="https://maps.google.com/maps/api/js?key=AIzaSyDgYcxk-Y-vMaD0WU0CQ0qS8RZuUC1NgKg&callback=initialize" async defer></script>

<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>

<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'>
</script> <!-- only if you need custom infoboxes -->




<%= form_for(@service) do |f| %>
  <% if @service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% @service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.check_box :status %>
  </div>

<div class="field">
    <%= f.label :coordinates %><br>
    <%= f.text_field :coordinates %>
</div>

  <div class="actions">
    <%= f.submit %>
  </div>






<!--<script type="text/javascript"
        src="https://maps.googleapis.com/maps/api/js?libraries=drawing\&key=AIzaSyAuH-_kmJzyQ9lCmsI2a6TsxvvVAl23s28">
</script>
 Geocoder.coordinates("La hechicera, Merida, Venezuela") -->




<h2>H2 here</h2>
<div id="map-container">
  <div id="map">
  </div>
</div>




<!-- <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAuH-_kmJzyQ9lCmsI2a6TsxvvVAl23s28"></script> 
<script type="text/javascript">
      map;
  function initialize() {
    var myOptions = {
      center: new google.maps.LatLng(lat, lon)
    };
    map = new google.maps.Map(document.getElementById('map_canvas'),
        myOptions);
  }

  google.maps.event.addDomListener(window, 'load', initialize);
</script>
<div id="map_canvas"></div>
-->




<% end %>

app/views/services/edit.html.erb
<h1>Editing Service</h1>

<%= render 'form' %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Services</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Category</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= service.name %></td>
        <td><%= service.description %></td>
        <td><%= service.category %></td>
        <td><%= service.status %></td>
        <td><%= link_to 'Show', service %></td>
        <td><%= link_to 'Edit', edit_service_path(service) %></td>
        <td><%= link_to 'Destroy', service, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service', new_service_path %>

app/views/services/new.html.erb
<h1>New Service</h1>

<%= render 'form' %>

<%= link_to 'Back', services_path %>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @service.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @service.description %>
</p>

<p>
  <strong>Category:</strong>
  <%= @service.category %>
</p>

<p>
  <strong>Status:</strong>
  <%= @service.status %>
</p>

<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>